# Install and configure Docker on supported plattforms.
---

- name: Check base OS version requirements
  assert:
    that:
      - ansible_os_family == "RedHat"
      - ansible_distribution_major_version|int >= 7

- include_vars: "RedHat.yml"
  when: ansible_os_family == 'RedHat'

- include: install.yml

- include: configure.yml

- include: configure-daemon.yml
  when: ansible_docker_node_docker_opts != ''
